drop table mba.staging_data;
CREATE TABLE mba.staging_data
(
  filename character varying(100),
  conditions_timestamp timestamp,
  config_version character varying(10),
  app_version_code character varying(10),
  sim_operator_code character varying(10),
  enterprise_id character varying(25),
  app_version_name character varying(25),
  submission_type character varying(20),
  source_ip character varying(23),
  params_expired_timestamp timestamp,
  params_expired_success boolean,
  net_activity_timestamp timestamp,
  net_activity_success boolean,
  net_activity_bytes_in numeric(25,0),
  net_activity_max_bytes_in numeric(25,0),
  net_activity_bytes_out numeric(25,0),
  net_activity_max_bytes_out numeric(25,0),
  cpu_activity_timestamp timestamp,
  cpu_activity_success boolean,
  cpu_activity_max_average numeric(3,0),
  cpu_activity_read_average numeric(3,0),
  phone_identity_timestamp timestamp,
  phone_identity_model character varying(50),
  phone_identity_manufacturer character varying(20),
  phone_identity_os_version character varying(20),
  phone_identity_os_type character varying(20),
  network_timestamp_1 timestamp,
  network_phone_type_1 character varying(20) ,
  network_phone_type_code_1 numeric(5,0),
  network_sim_operator_code_1 character varying(20),
  network_connected_1 boolean,
  network_active_type_code_1 numeric(5,0),
  network_type_code_1 numeric(5,0),
  network_type_1 character varying(20),
  network_operator_name_1 character varying(100),
  network_active_type_1 character varying(20),
  network_operator_code_1 character varying(20),
  network_sim_operator_name_1 character varying(100),
  network_roaming_1 boolean,
  network_timestamp_2 timestamp,
  network_phone_type_2 character varying(20) ,
  network_phone_type_code_2 numeric(5,0),
  network_sim_operator_code_2 character varying(20),
  network_connected_2 boolean,
  network_active_type_code_2 numeric(5,0),
  network_type_code_2 numeric(5,0),
  network_type_2 character varying(20),
  network_operator_name_2 character varying(100),
  network_active_type_2 character varying(20),
  network_operator_code_2 character varying(20),
  network_sim_operator_name_2 character varying(100),
  network_roaming_2 boolean,  
  network_timestamp_3 timestamp,
  network_phone_type_3 character varying(20),
  network_phone_type_code_3 numeric(5,0),
  network_sim_operator_code_3 character varying(20),
  network_connected_3 boolean,
  network_active_type_code_3 numeric(5,0),
  network_type_code_3 numeric(5,0),
  network_type_3 character varying(20),
  network_operator_name_3 character varying(100),
  network_active_type_3 character varying(20),
  network_operator_code_3 character varying(20),
  network_sim_operator_name_3 character varying(100),
  network_roaming_3 boolean,
  gsm_cell_timestamp_1 timestamp,
  gsm_cell_umts_psc_1 numeric(10,0),
  gsm_cell_signal_strength_1 numeric(15,5),
  gsm_cell_location_area_code_1 numeric(10,0),
  gsm_cell_bit_error_rate_1 numeric(10,5),
  gsm_cell_cell_tower_id_1 character varying(25),
  gsm_cell_timestamp_2 timestamp,
  gsm_cell_umts_psc_2 numeric(10,0),
  gsm_cell_signal_strength_2 numeric(15,5),
  gsm_cell_location_area_code_2 numeric(10,0),
  gsm_cell_bit_error_rate_2 numeric(10,5),
  gsm_cell_cell_tower_id_2 character varying(25),
  gsm_cell_timestamp_3 timestamp,
  gsm_cell_umts_psc_3 numeric(10,0),
  gsm_cell_signal_strength_3 numeric(15,5),
  gsm_cell_location_area_code_3 numeric(10,0),
  gsm_cell_bit_error_rate_3 numeric(10,5),
  gsm_cell_cell_tower_id_3 character varying(25),
  location_timestamp_1 timestamp,
  location_longitude_1 numeric(10,6),
  location_latitude_1 numeric(10,6),
  location_location_type_1 character varying(25),
  location_accuracy_1 numeric(20,10),
  location_timestamp_2 timestamp,
  location_longitude_2 numeric(10,6),
  location_latitude_2 numeric(10,6),
  location_location_type_2 character varying(25),
  location_accuracy_2 numeric(20,10),
  location_timestamp_3 timestamp,
  location_longitude_3 numeric(10,6),
  location_latitude_3 numeric(10,6),
  location_location_type_3 character varying(25),
  location_accuracy_3 numeric(20,10),
  location_timestamp_4 timestamp,
  location_longitude_4 numeric(10,6),
  location_latitude_4 numeric(10,6),
  location_location_type_4 character varying(25),
  location_accuracy_4 numeric(20,10),
  get_timestamp timestamp,
  get_success boolean,
  get_number_of_threads numeric(3,0),
  get_warmup_bytes numeric(20,0),
  get_warmup_time numeric(20,0),
  get_transfer_bytes numeric(20,0),
  get_transfer_time numeric(20,0),
  get_bytes_sec numeric(20,0),
  get_target character varying(100),
  get_target_ipaddress character varying(23),
  post_timestamp timestamp,
  post_success boolean,
  post_number_of_threads numeric(3,0),
  post_warmup_bytes numeric(20,0),
  post_warmup_time numeric(20,0),
  post_transfer_bytes numeric(20,0),
  post_transfer_time numeric(20,0),
  post_bytes_sec numeric(20,0),
  post_target character varying(100),
  post_target_ipaddress character varying(23),
  latency_timestamp timestamp,
  latency_success boolean,
  latency_rtt_avg numeric(20,0),
  latency_rtt_min numeric(20,0),
  latency_rtt_max numeric(20,0),
  latency_rtt_stddev numeric(20,0),
  latency_received_packets numeric(20,0),
  latency_lost_packets numeric(20,0),
  latency_target character varying(100),
  latency_target_ipaddress character varying(23));
  
copy bbmap.staging_data from 'C:/mmba/samknows.csv' with (delimiter '~', header true, format csv , NULL '\N');  
